name = "TransitionMatrices"
uuid = "057c4241-e127-4181-840e-6b4b92e6eef5"
version = "0.3.1"
authors = ["Gabriel Wu <wuzihua@pku.edu.cn> and contributors"]

[deps]
Arblib = "fb37089c-8514-4489-9461-98f9c8763369"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StableTasks = "91464d47-22a1-43fe-8b7f-2d57ee82463f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"
Wigxjpf = "af901252-fd8a-4391-8647-10b4fde07a1e"

[compat]
Arblib = "1"
DoubleFloats = "1"
FastGaussQuadrature = "1"
ForwardDiff = "1"
GenericLinearAlgebra = "0.3"
OffsetArrays = "1"
Quadmath = "0.5"
Rotations = "1"
StableTasks = "0.1.7"
StaticArrays = "1"
TestItems = "1"
Wigxjpf = "0.2"
julia = "1.10"
